config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  devise_for :users
  resources :projects do 
    resources :improvements do
      resources :items
      resources :states
    end
  end

  root 'welcome#index'

end

app/models/improvement.rb
class Improvement < ActiveRecord::Base
	belongs_to :project
	has_and_belongs_to_many :items
	has_many :states
end

app/models/information.rb
class Information < ActiveRecord::Base
	belongs_to :item

	def self.name_from_items(items)
		Information.select("information.name").where("information.item_id in (?) and information.name is not null",items.map(&:id)).distinct
	end
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :state
	has_many :information
	has_and_belongs_to_many :improvements
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :improvements
end

app/models/state.rb
class State < ActiveRecord::Base
	belongs_to :improvement
	has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :projects	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/improvements_controller.rb
class ImprovementsController < ApplicationController
  before_action :set_improvement, only: [:show, :edit, :update, :destroy]

  def index
    @improvements = Improvement.all
  end

  def show
  end

  def new
    @improvement = Improvement.new
  end

  def edit
  end

  def create
    @project = Project.find(params[:project_id])
    @improvement = @project.improvements.create(improvement_params)
    redirect_to @project, notice: 'Improvement was successfully created.'
  end

  # PATCH/PUT /improvements/1
  # PATCH/PUT /improvements/1.json
  def update
    respond_to do |format|
      if @improvement.update(improvement_params)
        format.html { redirect_to @improvement, notice: 'Improvement was successfully updated.' }
        format.json { render :show, status: :ok, location: @improvement }
      else
        format.html { render :edit }
        format.json { render json: @improvement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /improvements/1
  # DELETE /improvements/1.json
  def destroy
    @improvement.destroy
    respond_to do |format|
      format.html { redirect_to improvements_url, notice: 'Improvement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_improvement
      @project = Project.find(params[:project_id])
      @improvement = @project.improvements.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def improvement_params
      params.require(:improvement).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def create
  	@improvement = Improvement.find(params[:improvement_id])
    @item = @improvement.items.create(item_params)
    redirect_to project_improvement_path(params[:project_id], @improvement), notice: 'Improvement was successfully created.'
  end

  def edit
    @project = Project.find(params[:project_id])
    @improvement = Improvement.find(params[:improvement_id])  
    @item = @improvement.items.find(params[:id])
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @improvement = Improvement.find(params[:improvement_id])  
    @item = @improvement.items.find(params[:id])
    @item.update(item_params)
    redirect_to project_improvement_url(params[:project_id], params[:improvement_id]), notice: 'Item was successfully updated.'
  end

  def destroy
    @improvement = Improvement.find(params[:improvement_id])
    @improvement.items.destroy(params[:id])
    redirect_to project_improvement_url(params[:project_id], params[:improvement_id]), notice: 'Item was successfully destroyed.'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @improvement = Improvement.find(params[:improvement_id])	
      @item = @improvement.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :state_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.users.push(current_user)
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
      else
        format.html { render :index }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def create
  	@improvement = Improvement.find(params[:improvement_id])	
    @state = @improvement.states.create(state_params)
    redirect_to project_improvement_path(params[:project_id], @improvement), notice: 'Improvement was successfully created.'
  end

  def destroy
    @improvement = Improvement.find(params[:improvement_id])
    @improvement.states.destroy(params[:id])
    redirect_to project_improvement_url(params[:project_id], params[:improvement_id]), notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @improvement = Improvement.find(params[:improvement_id])
      @state = @improvement.states.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/improvements_helper.rb
module ImprovementsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/changes/_form.html.erb
<%= form_for(@change) do |f| %>
  <% if @change.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@change.errors.count, "error") %> prohibited this change from being saved:</h2>

      <ul>
      <% @change.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/improvements/_form.html.erb
<%= form_for(@improvement) do |f| %>
  

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/improvements/edit.html.erb
<h1>Editing Improvement</h1>

<%= render 'form' %>

<%= link_to 'Show', @improvement %> |
<%= link_to 'Back', improvements_path %>

app/views/improvements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Improvements</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @improvements.each do |improvement| %>
      <tr>
        <td><%= improvement.name %></td>
        <td><%= link_to 'Show', improvement , {:class => 'btn btn-primary'}%></td>
        <td><%= link_to 'Edit', edit_project_improvements_path(improvement), {:class => 'btn btn-warning'} %></td>
        <td><%= link_to 'Destroy', improvement, method: :delete, data: { confirm: 'Are you sure?' }, {:class => 'btn btn-danger'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Improvement', new_project_improvements_path, {:class => 'btn btn-primary'} %>

app/views/improvements/new.html.erb
<h1>New Improvement</h1>

<%= render 'form' %>

<%= link_to 'Back', improvements_path %>

app/views/improvements/show.html.erb
<p id="notice"><%= notice %></p>
<ol class="breadcrumb">
    <li><%= link_to 'My Projects', projects_path %></li>
    <li><%= link_to "#{@project.name}", @project %></li>
    <li><%= link_to "#{@improvement.name}", [@project, @improvement] %></li>
</ol>


<h2>States</h2>
<% @improvement.states.each do |state| %>
<span class="label label-default"><%= state.name %>
  <%= link_to url_for([@project, @improvement, state]), 
      method: :delete, data: { confirm: 'Are you sure?' } do %>
    | &times;
<% end %>
</span>
<% end %>
<span class="label label-primary">
<a href="#" data-toggle="modal" data-target="#state-form">
        Add State <i class="fa fa-plus"></i>
        </a>
</span>

<div class="modal fade" id="state-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <%= form_for([@project, @improvement, @improvement.states.build]) do |f| %>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">State</h4>
            </div>

            <div class="modal-body">

                <div class="field">
                    <%= f.label :name %><br>
                    <%= f.text_field :name %>
                </div>

            </div>

            <div class="modal-footer">
                <%= f.submit 'Save', :class => 'btn btn-primary' %>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
            <% end %>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <h2>Items</h2>
    </div>
    <div class="col-md-4">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#item-form">
        Add Item
        </button>
    </div>
</div>

<table class="table table-striped">
    <thead>
        <th>Description</th>
        <% Information.name_from_items(@improvement.items).each do |info| %>
        	<th> <%= info.name %> </th>
        <% end %>
        <th>State</th>
        <th></th>
    </thead>
    <% @improvement.items.each do |item| %>
    <tr>
        <td>
            <%= item.description %>
        </td>
    	<% item.information.each do |info| %>
           <td> <%= info.value %></td>
            <% end %>	
        <td>
            <% unless item.state.nil? %>
            <%= item.state.name %>
            <% end %>
        </td>
        <td>
        <div class="btn-group">
          <%= link_to 'Edit', edit_project_improvement_item_path(@project, @improvement, item) , :class => 'btn btn-warning' %>
          <%= link_to 'Delete', url_for([@project, @improvement, item]), 
      method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </div>
        </td>
    </tr>
    <% end %>
</table>
<div class="modal fade" id="item-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <%= form_for([@project, @improvement, @improvement.items.build]) do |f| %>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">State</h4>
            </div>

            <div class="modal-body">

                <div class="field">
                    <%= f.label :description %><br>
                    <%= f.text_field :description %>
                </div>
                
                <% Information.name_from_items(@improvement.items).each do |info| %>
                <div class="field">
        			<label><%= info.name %></label>
        			<input type="text" name="">
        			</div>	
        		<% end %>
                <div class="field">
                    <%= select("item", "state_id", State.all.collect {|s| [ s.name, s.id ] }) %>
                </div>
            </div>

            <div class="modal-footer">
                <%= f.submit 'Save', :class => 'btn btn-primary' %>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/items/edit.html.erb
<%= form_for([@project, @improvement, @item]) do |f| %>
    <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
    </div>
    <div class="field">
        <%= select("item", "state_id", State.all.collect {|s| [ s.name, s.id ] }) %>
    </div>
    <%= f.submit 'Save', :class => 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Asura</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <%= link_to 'Asura',  root_path, { :class=>"navbar-brand" } %>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <% if user_signed_in? %>
                        <li>
                        <a href="">
                            <%= current_user.email %>
                            </a>
                        </li>
                        <li>
                            <%= link_to 'My Projects', projects_path %>
                        </li>
                        <li>

                        	<%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }  %>
                        </li>
                        <% else %>
                        <li>
                            <%= link_to 'Sign Up', new_user_registration_path %>
                        </li>
                        <li>
                            <%= link_to 'Login', new_user_session_path %>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
        <%= yield %>
        </div>
    </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <ul>
<% @project.users.each do |user| %>
    <li> <%= user.email %></li>
<% end %>
</ul>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<ol class="breadcrumb">
  <li><%= link_to 'My Projects', projects_path %></li>
</ol>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Improvements</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @projects.each do |project| %>
        <tr>
            <td><%= project.name %></td>
            <td><%= project.improvements.size %></td>
            <td>
            <div class="btn-group" role="group">
            <%= link_to 'View', project, :class => 'btn btn-primary' %>
            <%= link_to 'Edit', edit_project_path(project) , :class => 'btn btn-warning' %>
            <%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
            </div>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
<br>
<button class="btn btn-primary" data-toggle="modal" data-target="#project-form" >New Project</button>
<div class="modal fade" id="project-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <%= form_for(Project.new) do |f| %>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Improvement</h4>
            </div>

            <div class="modal-body">

                <div class="field">
                    <%= f.label :name %><br>
                    <%= f.text_field :name %>
                </div>

            </div>

            <div class="modal-footer">
                <%= f.submit 'Save', :class => 'btn btn-primary' %>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<ol class="breadcrumb">
  <li><%= link_to 'My Projects', projects_path %></li>
  <li><%= link_to "#{@project.name}", @project %></li>
</ol>

<div class="row">
    <div class="col-md-8">
        <h2>Improvements</h2>
    </div>
    <div class="col-md-4">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#improvement-form">
        Create Improvement
        </button>
    </div>
</div>
<table class="table table-striped">
    <thead>
        <th>
            Name
        </th>
        <th>Items</th>
        <th></th>
    </thead>
    <% @project.improvements.each do |improvement| %>
    <tr>
        <td>
            <%= improvement.name %>
        </td>
        <td>
          <%= improvement.items.size %>
        </td>
        <td>
            <%= link_to 'View', project_improvement_path(@project, improvement), {:class => 'btn btn-primary'} %>
        </td>
    </tr>
    <% end %>
</table>

<div class="modal fade" id="improvement-form">
    <div class="modal-dialog">
        <div class="modal-content">
                <%= form_for([@project, @project.improvements.build]) do |f| %>   
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Improvement</h4>
            </div>
            
            <div class="modal-body">
        
                <div class="field">
                    <%= f.label :name %><br>
                    <%= f.text_field :name %>
                </div>
                
            </div>
            
            <div class="modal-footer">
                <%= f.submit 'Save', :class => 'btn btn-primary' %>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        <% end %>
        </div>
    </div>
</div>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/states/create.html.erb
<h1>States#create</h1>
<p>Find me in app/views/states/create.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Asura</h1>
<p>Improve your project with power and knowledge</p>